message: Development mode is on

#spring:
#  h2:
#    console:
#      enabled: true
#      path: /h2
#  datasource:
#    url: jdbc:h2:mem:dev
#    username: sa
#    password:
#    driverClassName: org.h2.Driver
#  jpa:
#    show-sql: true
#    defer-datasource-initialization: true

spring:
  datasource:
    username: postgres
    url: jdbc:postgresql://localhost:5432/desafio
    platform: postgres
    password: postgres
    initialization-mode: always
    sql:
      init:
        mode: always
  jpa:
    database: POSTGRESQL
    show-sql: 'true'
    defer-datasource-initialization: 'true'
    hibernate:
      ddl-auto: create-drop
  database:
    driverClassName: org.postgresql.Driver

security:
  oauth2:
    resource:
      filter-order: 3

oauth:
  client:
    name: client
    secret: secret

jwt:
  secret: MY-JWT-SECRET